---
members:
  - id: 0252b905-ecdd-49c3-8103-368ef556d66e
    name: loxygen
    contacts:
      twitter: loxygenK
      github: loxygenK
  - id: 9a91b7b6-4263-4a33-9193-e4cedbab816d
    name: いっそう
    contacts:
      twitter: kousou4129
      github: isso0424
  - id: 5ab2de37-1808-4b38-9957-b8eccb47512b
    name: 鏡華
    contacts:
      twitter: mirror_kt
      github: mirror-kt
  - id: 80914a39-1cdf-4fa3-b0cc-4e5d4c59189d
    name: でみ
    contacts:
      twitter: Sw_Saturn
      github: Sw-Saturn
  - id: 4c62f06f-d7fd-4ae2-8a3a-4e059c7984c2
    name: にとふ
    contacts:
      twitter: 2tfuyu
      github: nitf
  - id: 0f418ed4-ec09-4e41-8994-9444a87e6a58
    name: Mikuro さいな
    contacts:
      twitter: MikuroXina
      github: MikuroXina
  - id: e10719bc-b078-425d-bbd3-0e402e2b4908
    name: かわえもん
    contacts:
      twitter: kawason0708
      github: kawaemon
  - id: 24905712-0078-4adb-8a68-b86903d4540a
    name: kakao.
    contacts:
      twitter: e381x
      github: kakao1839
  - id: b766fdbb-bbc5-420d-873e-92323fbf8093
    name: Siketyan
    contacts:
      twitter: ch1aic
      github: Siketyan
  - id: 11450c51-09c5-445f-ac69-d115daf9efc2
    name: raiga0310
    contacts:
      twitter: raiga_tech
      github: raiga0310
  - id: 16d7eadf-829c-4f94-b8a5-7e58be45a244
    name: Bony Chops
    contacts:
      twitter: BonyChops
      github: BonyChops
  - id: c0b161b5-84b8-46c5-9b29-75c4d6da6ac1
    name: ぽちゃまあ
    contacts:
      twitter: PotyaExe
      github: potyama
  - id: 35bd3291-65fb-4b2e-b0a6-8b8b5dddb54e
    name: ゆにおか
    contacts:
      twitter: UniokaWorld
      github: UniokaWorld
  - id: 37816472-13ee-4ca8-9db7-e44e61297a46
    name: unios103
    contacts:
      twitter: unios103
      github: unios103
  - id: 6be77fa2-a469-4eab-9941-3120035761eb
    name: SHUN / しゅん
    contacts:
      twitter: programmer_shun
      github: shun-shobon
  - id: d4189032-ca16-46f7-a704-2dba36a697b1
    name: sou
    contacts:
      twitter: is_stone_saw
      github: stonesaw
  - id: 227d3390-77eb-4fea-a464-6fbc3ad47f40
    name: たひ
    contacts:
      twitter: Tahi_knct
      github: Tahi-knct
  - id: ce8ebd4f-bf5c-4254-964f-44d9033cb00b
    name: おのかちお
    contacts:
      twitter: onokatio_
      github: onokatio
  - id: bc6540ec-3ad1-4e19-8159-e29fe4bb1f7c
    name: おりかげ
    contacts:
      twitter: _orikage
      github: ~
  - id: 0d23a296-b3d8-45d0-b95d-dd4e80a13b66
    name: かさごん
    contacts:
      twitter: Kasagone
      github: m17saitou
  - id: c8e84e15-8710-48c6-9af1-087540c35833
    name: てぃけ
    contacts:
      twitter: tky_sleep
      github: ~
  - id: 4d8376a5-b894-40b3-8cbc-66dff5539709
    name: ねこ（はせがわ）
    contacts:
      twitter: ~
      github: ~
  - id: 9c38ac46-fccd-495d-9b71-d54eb84fe2ab
    name: watαno
    contacts:
      twitter: oxLC_theta
      github: watano1168
  - id: 65ad58b5-27e3-4d4b-adc5-442c9971e35a
    name: 某さん
    contacts:
      twitter: nanigasi_3
      github: nanigasi-san
  - id: 38032822-e97f-445e-8416-62be0026d195
    name: Yu
    contacts:
      twitter: ~
      github: ~
  - id: 695ca68e-cad8-4a80-a182-a8f4872b745b
    name: かんたろう
    contacts:
      twitter: kantarow_
      github: kantarow
  - id: dbb7cc9d-00cd-4d67-9f59-fb33d051c784
    name: チャハーン
    contacts:
      twitter: Chaha1n
      github: Chaha1n
  - id: 96c953e6-4d96-497f-be87-7b47e99135d3
    name: フレキシブル基板
    contacts:
      twitter: FPC_COMMUNITY
      github: FlexiblePrintedCircuits
  - id: 78ee0fcd-1dc1-4c80-a9b0-664e4a03da40
    name: Lockdef
    contacts:
      twitter: LockDef
      github: Lockdef
  - id: 1f19d1fb-4798-429f-8b80-9fe1e205d54e
    name: ぬーべすと
    contacts:
      twitter: facking_noobest
      github: noobest19s
  - id: c0a5c7c1-8a56-426e-b382-accce1762fb5
    name: fof
    contacts:
      twitter: 403_fof
      github: ~
  - id: 53f7bf58-7fdf-43de-a812-9f93ab752e17
    name: Lino_Ren
    contacts:
      twitter: alpha_linoren
      github: ~
  - id: 138af419-6b5d-498c-b16b-b93ed74f17c5
    name: 寄り目
    contacts:
      twitter: Yorime_yrm
      github: ~
  - id: f05b7dec-bdd9-466e-a18b-2f30ce8d6fc5
    name: 柚月えふ
    contacts:
      twitter: left_an1
      github: ~
  - id: 94024fd0-1c9d-4a2d-835f-bc208a2efa90
    name: ソーシ
    contacts:
      twitter: soshi_harami
      github: soshiharami
  - id: f31a362b-3235-476b-be86-d70c9b682490
    name: Laminne33569
    contacts:
      twitter: laminne33569
      github: laminne
  - id: 6bfc4277-2e5b-4473-b889-6a8c7fad3964
    name: 白兎
    contacts:
      twitter: siroRabi_jk
      github: ~
  - id: add61737-7010-4d3b-9e97-b54394bc7d7b
    name: Nanai10a
    contacts:
      twitter: 771tenNext
      github: nanai10a
  - id: 43572f6b-c8d1-4f19-9a59-f03ee3382541
    name: 西行響希
    contacts:
      twitter: Saigyo_HBK
      github: HimHim1113
  - id: f4178ba4-c841-4acf-9400-da8e1ca4cb88
    name: とすあっぷ
    contacts:
      twitter: tos_up
      github: tos-up
  - id: 39b752b2-5abc-4c5e-9737-757c37e390c9
    name: Nii
    contacts:
      twitter: niiLoveA320ceo
      github: ~
  - id: acf86683-3dc6-4faa-95be-faaea5b3de86
    name: しぐま
    contacts:
      twitter: sigumaaaaa
      github: Sigumaa
  - id: bf8f1323-eadb-42aa-833f-d5a55810d012
    name: 宮野 慧
    contacts:
      twitter: miyacorata
      github: miyacorata
  - id: afa94720-49b1-48da-a07d-70b2ddda81ea
    name: ねんね
    contacts:
      twitter: nai_ber
      github: nenne
  - id: 44d73d92-6909-4f95-8876-672e81625a4f
    name: りゅうと
    contacts:
      twitter: rtx_gh
      github: ~
  - id: 555d9dd2-8e83-49c1-b342-bdefab4a9f03
    name: Yusuke
    contacts:
      twitter: idoit_do
      github: ~
  - id: 1378bcc6-f356-45ba-8755-1a8416d90a47
    name: えぬ
    contacts:
      twitter: N3JABEE
      github: ~
  - id: 482e222e-27de-4542-af8d-17600420198d
    name: Okaka
    contacts:
      twitter: ~
      github: ~
  - id: 0d00e0aa-5ed6-423e-8b21-1fade2490750
    name: なぎねる
    contacts:
      twitter: tirun61031a_o_a
      github: ~
  - id: 2d57dedb-a688-4089-99a4-cc47d4b7fa5b
    name: こるく
    contacts:
      twitter: Colk_
      github: Colk-tech
  - id: 0925ae68-d414-473b-a3e0-9e8e40dac483
    name: ko
    contacts:
      twitter: ko_CottonLove
      github: ko50
  - id: 55fc9a0d-a1e1-4cee-a794-8285323253c7
    name: foobar
    contacts:
      twitter: ~
      github: ~
