name: Rust

on:
  - push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt,clippy

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

      - uses: actions/upload-artifact@v2
        with:
          name: members-db
          path: target/debug/members-db

  distribute:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: members-db

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.BOT_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.BOT_KNOWN_HOSTS }}

      - name: Configure Git
        run: |
          git config --global user.name Haseyu
          git config --global user.email bot@nittc-programming.club

      - name: Clone members-db-dist repository
        run: git clone git@github.com:NITTC-ComputerClub/members-db-dist.git public

      - name: Build members database
        run: chmod +x ./members-db && ./members-db build

      - name: Distribute to members-db-dist
        run: cd public && git add . && git commit --allow-empty -m "$(date)" && git push
